name: Ruff

on: push

jobs:
  ruff:
    runs-on: ubuntu-slim
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed python files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96
        with:
          files: |
            **/*.py

      - name: Run Ruff check on changed files
        if: steps.changed-files.outputs.any_changed == true
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89
        with:
          args: "check --output-format=github ${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Run Ruff format check on changed files
        if: steps.changed-files.outputs.any_changed == true
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89
        with:
          args: "format --check ${{ steps.changed-files.outputs.all_changed_files }}"
